version: '3.4'

networks:
  dev:
    driver: bridge

services:
  authenticationservice:
    image: docker.io/library/authenticationservice
    depends_on:
      - "usersserver"s
    container_name: authenticationservice-container
    ports:
      - "8088:80"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=usersserver;Port=5432;Database=Users;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  usersserver:
    image: postgres:latest
    container_name: usersserver
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Users
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/volumes/
    networks:
      - dev
    
volumes:
  app_data:
